baseURL = 'https://shreerammodi.com'
languageCode = 'en-us'
title = 'Shreeram Modi'

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "PGP"
    url = "/pgp/"
    weight = 20
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 30

[params]
  homeText = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
